[project]
name = "state-estimation-simulations"
version = "0.1.0"
description = "A collection of simulations for state estimation."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "opencv-python",
    "scikit-learn",
    "scipy",
    "matplotlib",
    "manifpy",
]

[dependency-groups]
dev = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.uv.sources]
manifpy = { path = "../manif" }
