'''
Compares two ways of integrating a noisy IMU (gyro + body-frame velocity) stream
into a pose estimate:

  1. "naive" - orientation kept as a 3-vector of Euler angles (roll, pitch, yaw),
     updated by directly adding the measured body angular rate: euler += omega*dt.
     This treats SO(3) as if it were a flat vector space, which is only valid to
     first order and breaks down as soon as the attitude has any appreciable
     rotation (it ignores the nonlinear Euler-rate kinematic transform).

  2. "expmap" - orientation kept as a rotation matrix, updated on the SO(3)
     manifold itself: R *= Exp(omega*dt), using the closed-form Rodrigues formula.

Both estimators consume the *same* noisy measurements each step, so any gap
between them isolates the error introduced by the naive vector-space
approximation itself (on top of the noise both share), rather than being an
artifact of different noise draws.

Ground truth is generated by exp-map-integrating the noise-free rates, which is
exact under the zero-order-hold assumption of constant rate within each dt.

Appendix:
- Gyroscopes: Measure angular velocity (rotation rate in degrees per second, °/s) around the X, Y, and Z axes. 
    Integrating angular velocity over time gives you the change in orientation (angles like roll, pitch, and yaw).
- Accelerometers: Measure linear acceleration (m/s²) along the X, Y, and Z axes. 
    By integrating acceleration over time, you can estimate velocity, and by integrating velocity, you can estimate position. 
    However, this double integration can lead to significant drift over time due to noise and biases in the measurements.

'''

import argparse
import os
import sys

import numpy as np
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from lie_utils import so3_exp, rotation_geodesic_error
from utils import true_body_rates


def euler_to_R(rpy):
    """Convert ZYX (roll-pitch-yaw) Euler angles to rotation matrix."""
    roll, pitch, yaw = rpy
    cr, sr = np.cos(roll), np.sin(roll)
    cp, sp = np.cos(pitch), np.sin(pitch)
    cy, sy = np.cos(yaw), np.sin(yaw)
    Rx = np.array([[1, 0, 0], [0, cr, -sr], [0, sr, cr]])
    Ry = np.array([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]])
    Rz = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]])
    return Rz @ Ry @ Rx


def run_simulation(duration, dt, gyro_noise_std, vel_noise_std, seed):
    """Simulation of naive vs. exp-map integration of noisy IMU measurements.

    Args:
        duration: Simulation length in seconds
        dt: IMU sample interval in seconds
        gyro_noise_std: Standard deviation of gyroscope noise
        vel_noise_std: Standard deviation of velocity noise
        seed: Random seed

    Returns:
        t_hist: Simulation history (time steps)
        rot_err_naive: Rotation error for naive estimator
        rot_err_exp: Rotation error for exp-map estimator
        pos_err_naive: Position error for naive estimator
        pos_err_exp: Position error for exp-map estimator
    """
    
    rng = np.random.default_rng(seed)
    n_steps = int(duration / dt)

    # ground truth attitude state (rotation matrix) and position state (3D vector)
    R_gt_naive, p_gt_naive = np.eye(3), np.zeros(3)
    R_gt_exp, p_gt_exp = np.eye(3), np.zeros(3)
    
    # naive estimator's own attitude state (roll,pitch,yaw)
    R_est_naive_euler = np.zeros(3)   
    R_est_naive, p_est_naive = np.eye(3), np.zeros(3)
    
    # exp-map estimator's own attitude state (rotation matrix)
    R_est_exp, p_est_exp = np.eye(3), np.zeros(3)

    t_hist = np.zeros(n_steps)
    
    # rotation error + position error for naive estimator
    rot_err_naive = np.zeros(n_steps)
    pos_err_naive = np.zeros(n_steps)

    # rotation error + position error for exp-map estimator
    rot_err_exp = np.zeros(n_steps)
    pos_err_exp = np.zeros(n_steps)

    for k in range(n_steps):
        
        t = k * dt
        
        # Ground truth: get the true body rates (angular velocity and linear velocity) at time t
        omega_gt, v_gt = true_body_rates(t)

        # Ground truth: naive integration of the noise-free rates using Euler angles (roll, pitch, yaw)
        R_gt_naive = R_gt_naive @ euler_to_R(omega_gt * dt)
        p_gt_naive = p_gt_naive + R_gt_naive @ v_gt * dt

        # Ground truth: exact SO(3) integration of the noise-free rates.
        R_gt_exp = R_gt_exp @ so3_exp(omega_gt * dt)
        p_gt_exp = p_gt_exp + R_gt_exp @ v_gt * dt

        # Shared noisy IMU measurement.
        
        # Gyroscope noise: Gaussian noise added to the true angular velocity.
        # This simulates the effect of sensor noise on the angular velocity measurements from gyroscope.
        omega_meas = omega_gt + rng.normal(0.0, gyro_noise_std, 3)
        
        # Body-velocity noise: Gaussian noise added to the true body-frame velocity.
        # This simulates the effect of sensor noise on the linear velocity measurements from accelerometer.
        v_meas = v_gt + rng.normal(0.0, vel_noise_std, 3)

        # Naive: Euler angles treated as a flat vector space.
        R_est_naive_euler = R_est_naive_euler + omega_meas * dt
        R_est_naive = euler_to_R(R_est_naive_euler)
        p_est_naive = p_est_naive + R_est_naive @ v_meas * dt

        # Exp-map: proper SO(3) manifold update.
        R_est_exp = R_est_exp @ so3_exp(omega_meas * dt)
        p_est_exp = p_est_exp + R_est_exp @ v_meas * dt

        t_hist[k] = t
        rot_err_naive[k] = np.degrees(rotation_geodesic_error(R_gt_naive, R_est_naive))
        rot_err_exp[k] = np.degrees(rotation_geodesic_error(R_gt_exp, R_est_exp))
        pos_err_naive[k] = np.linalg.norm(p_gt_naive - p_est_naive)
        pos_err_exp[k] = np.linalg.norm(p_gt_exp - p_est_exp)

    return t_hist, rot_err_naive, rot_err_exp, pos_err_naive, pos_err_exp


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--duration", type=float, default=20.0, help="Simulation length in seconds")
    parser.add_argument("--dt", type=float, default=0.005, help="IMU sample interval in seconds")
    parser.add_argument("--gyro-noise-std", type=float, default=0.02, help="Gyro noise std-dev (rad/s)")
    parser.add_argument("--vel-noise-std", type=float, default=0.05, help="Body-velocity noise std-dev (m/s)")
    parser.add_argument("--seed", type=int, default=0, help="RNG seed")
    parser.add_argument("--out", type=str, default=None, help="Save the figure to this path instead of showing it")
    args = parser.parse_args()

    t, rot_err_naive, rot_err_exp, pos_err_naive, pos_err_exp = run_simulation(
        args.duration, args.dt, args.gyro_noise_std, args.vel_noise_std, args.seed,
    )

    fig, (ax_rot, ax_pos) = plt.subplots(2, 1, figsize=(9, 7), sharex=True)

    ax_rot.plot(t, rot_err_naive, label="naive (Euler-angle, vector-space)", color="tab:red")
    ax_rot.plot(t, rot_err_exp, label="Exp-map (SO(3))", color="tab:blue")
    ax_rot.set_ylabel("Rotation error (deg)")
    ax_rot.set_yscale("log")
    ax_rot.legend()
    ax_rot.set_title("Attitude error: naive Euler-angle vs. SO(3) Exp-map integration")

    ax_pos.plot(t, pos_err_naive, label="naive (Euler-angle, vector-space)", color="tab:red")
    ax_pos.plot(t, pos_err_exp, label="Exp-map (SE(3))", color="tab:blue")
    ax_pos.set_ylabel("Position error (m)")
    ax_pos.set_xlabel("Time (s)")
    ax_pos.set_yscale("log")
    ax_pos.legend()

    fig.tight_layout()
    if args.out:
        fig.savefig(args.out, dpi=150)
        print(f"Saved figure to {args.out}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
